### ISSUE TITLE
Outputs don't have defined coordinate systems

### ISSUE THREAD

**Issue by Hornbydd** [giswqs/WhiteboxTools-ArcGIS#14]
Just been testing the vector point to raster tool, I assume this is an issue in all tools that generate a raster as an output. My gut feeling this is an issue with WBT ( @jblindsay ) rather than the python toolbox, but could be wrong?

My input dataset is a point dataset with a British_National_Grid coordinate system, the resulting TIF raster has no coordinate system as shown below:

![image](https://user-images.githubusercontent.com/22773948/75394470-1bc87380-58e8-11ea-89c8-0fcb90624115.png)

I can run the define projection tool to set it to British_National_Grid.

I notice that if I feed this raster (with a coordinate system set) straight into a raster to vector polygon tool the output shapefile retains the coordinate system.

The output should not be loosing the coordinate system. 

I see two options:

1. If it is a bug in WBT then fix it.
2. If it is a limitation in WBT and rasters drop coordinate systems for what ever reason, then why not call the define projection tool within the execute() part of the function as a last step to ensure output has a valid coordinate system. Users should not be required to run the define projection tool when the input had a coordinate system.

**Comment by jblindsay** [comment]
Yes, this is the same issue that is reported [here](https://github.com/jblindsay/whitebox-tools/issues/57).

**Comment by giswqs** [comment]
Since this bug is related to the WBT backend, I will wait for @jblindsay to fix it when he has time. I will then update the ArcGIS frontend if needed.

**Comment by jblindsay** [comment]
Duncan, is there a particular tool/set of tools that you have noticed this characteristic of dropping projection information. I can only fix the ones that I am aware of that are demonstrating this behaviour.

**Comment by Hornbydd** [comment]
@jblindsay  At the moment I too am only aware that it this tool [vector point to raster] that causes the coordinate information to be dropped in the output raster. I assume its a relatively "easy" fix for you? I think what I can do is as I test/use tools then if I discover them I simply fire them off as an issue on the WBT repository and  not the ArcGIS toolbox?

**Comment by jblindsay** [comment]
@Hornbydd Yes, I actually made that change, along with adding this feature to the other vector-to-raster tools [four days ago](https://github.com/jblindsay/whitebox-tools/commit/11f0c4f911018f301da2e0076b7ee4d50dcdd5a4#diff-e12f53fb4260930de2b0d65a26dbf1c0).
