### ISSUE TITLE
ArcGIS Version this toolbox was designed for should be clearly stated.

### ISSUE THREAD

**Issue by JGaiot** [giswqs/WhiteboxTools-ArcGIS#18]
Hello.. I was initially excited to see an ArcGIS option available and read the readme file. I am running ArcGIS 10.4 but there was no indication of version this was developed for, so I gave it a try. It behaved painstakingly slow when initially loaded, similar to the 10.5 issue, but also creates an XML file for EVERY WBT command in the WBT folder where the toolbox is stored. One reason for the slow load time.. but it takes forever starting ArcMap when this tool is loaded, and the functions run but do nothing. I understand it is likely not compatible.. but my recommendation to you is to save people the heartache and just state Up Front - like perhaps in the readme file - what version ArcGIS this should be run in (e.g. 10.6 or above!). Because you can't assume everyone out there is running the latest and greatest. Thank you. JG

**Comment by JGaiot** [comment]
Upon further testing, I found one Data Tool which worked (Polygons to Lines). But none of the Hydro Analysis tools tested worked - the tools that I'm really interested in. This verifies a compatibility problem with 10.4.

**Comment by giswqs** [comment]
@JGaiot Thank you for the suggestion. I have added a note in the README to specify the supported ArcGIS versions. ArcMap always tries to create an XML file for every tool even it is not being used, which is insane and out of my control. ArcGIS Pro only creates a XML file when a tool is being used, which is much better. The toolbox can open instantly in ArcGIS Pro. 

Esri now Offers Students Free Access to Software for Continued Education through Coronavirus Closures ([source](https://www.esri.com/about/newsroom/announcements/esri-offers-students-free-access-to-software-for-continued-education-through-coronavirus-closures/)). You might want to check it out if you are qualified. 

Another workaround, you can install the [whitebox Python package](https://github.com/giswqs/whitebox-python#installation), which does not need ArcGIS. Then you can use the [WhiteboxTools Runner](https://github.com/giswqs/whitebox-python#whitebox-gui) to run any tools. Hope it helps. 

![](https://wetlands.io/file/images/whitebox.png)

**Comment by JGaiot** [comment]
Thanks for your response. I tend to be a thorough type, meaning I don't give up easily.. ;) I did further testing with the hydro analysis tools, and I originally assumed that being in an Arcmap environment, the tools would read Esri Grid format. But on a hunch, I converted to Tif and got results. Although the tool I ran (D8FlowAccumulation) resulted in a strange output. Cells are accumulating only to 255 and then they start over? By the way, I used a flow direction grid as input and specified it was in Esri format. I will have to do some more investigation...

So there seems to be some backwards compatibility with 10.4.. just so you know ;)

**Comment by JGaiot** [comment]
By the way, I did test the command line version as well, and got the same result.. so at least what I'm doing is repeatable in both methods.

**Comment by giswqs** [comment]
@JGaiot Input and output are handled by the [whitebox-tools](https://github.com/jblindsay/whitebox-tools) backend @jblindsay. You can [open an issue ](https://github.com/jblindsay/whitebox-tools/issues) on that repo if you encounter issues.

**Comment by JGaiot** [comment]
Okay thanks! If I can't troubleshoot the issue, I will post there. Cheers!
