### ISSUE TITLE
Hypsometric Analysis tool won´t run without watershed file 

### ISSUE THREAD

**Issue by monocilindro** [giswqs/WhiteboxTools-ArcGIS#26]
Tested out in ArcGIS Pro .  Watershed file is said to be optional. The tool won´t run without it

**Comment by giswqs** [comment]
This bug has been fixed. Please download the toolbox and try again.

**Comment by monocilindro** [comment]
Now it works. BTW, the issue is present in the Python version (whiteboxgui)

**Comment by giswqs** [comment]
@monocilindro Thanks for reporting. I just fixed the whiteboxgui bug. Please run `whiteboxgui.update_package()` in Jupyter/Colab once to install the latest version.
