### ISSUE TITLE
Red Exclamation point on ArcGIS WBT toolbox

### ISSUE THREAD

**Issue by JFlint23** [giswqs/WhiteboxTools-ArcGIS#35]
I upgraded to the 2.1 release and now when I go to use or connect to the toolbox it always shows a red exclamation point by the toolbox. I've tried deleting everything and re-extracting it all again to the same folder but the exclamation point still shows up.
![image](https://user-images.githubusercontent.com/101372571/157780379-8d954a2d-977f-496d-8214-8ab8236e7343.png)

**Comment by giswqs** [comment]
Thank you for reporting. It has been fixed. Please download [v2.1.1](https://github.com/giswqs/WhiteboxTools-ArcGIS/archive/refs/tags/v2.1.1.zip)

**Comment by JFlint23** [comment]
I downloaded it and it works now. Thanks! 🙂
________________________________
