### ISSUE TITLE
Compatibilidad WBT con ARCGIS PRO

### ISSUE THREAD

**Issue by gaaries** [giswqs/WhiteboxTools-ArcGIS#36]
**Instalado WTB en ARCGIS PRO como se indica https://github.com/giswqs/WhiteboxTools-ArcGIS#installation, con ello se apertura WTB en ARCGIS PRO visualizando las herramientas como tal pero al ejecutar se muestra un error:**
![WTB_ARCGISPRO_ERROR](https://user-images.githubusercontent.com/20585141/174224479-c0c335af-feb4-4139-b3da-d57b0bdaf9b0.png)
![WTB_ARCGISPRO_ERROR1](https://user-images.githubusercontent.com/20585141/174224575-1ac4529c-20f4-4a0f-a5a3-8fbe52434f91.png)

solicito un apoyo u orientación en el debido manejo de la caja de herramientas WTB en ARCGIS PRO.

**Comment by giswqs** [comment]
Unfortunately, GeoDatabase is not supported. You need to export features from GeoDatabase as shapefiles.
