### ISSUE TITLE
SmoothVegetationResidual Fails to open in ArcPro Toolbox

### ISSUE THREAD

**Issue by PBSUAS** [giswqs/WhiteboxTools-ArcGIS#37]
With the most recent WhiteboxTools-ArcGIS-master zip (downloaded today), as well as the first version I downloaded ~4 months ago, the "SmoothVegetationResidual" tool fails to open with the following error:
![image](https://user-images.githubusercontent.com/86683516/178572639-2f687c6a-5088-47b4-8fd1-a1909081f70c.png)
This error occurs prior to loading/selecting any files.   My version of WBT is licensed with the GTE and I can verify that other licensed tools succeed in opening and running. 

SmoothVegetationResidual also runs successfully when running from wb_runner.py
(Note: John Lindsay helped troubleshoot over chat and asked me to post the issue here, as it seems to be related to the Arc toolbox specifically)

**Comment by giswqs** [comment]
Do you mean that this is the only tool that fails and other GTE tools work fine with ArcGIS Pro?

**Comment by PBSUAS** [comment]
Correct, at least the other tools I've run so far.  Topo animation runs fine and produces an output - https://www.whiteboxgeo.com/manual/wbt_book/available_tools/geomorphometric_analysis.html#TopographicPositionAnimation

**Comment by giswqs** [comment]
I can open the tool with ArcGIS Pro 2.9.3. What ArcGIS Pro version are you using?

![image](https://user-images.githubusercontent.com/5016453/178577415-72e3a77a-f27d-45a6-bb81-2a347a728f4a.png)

**Comment by PBSUAS** [comment]
Same here.  
![image](https://user-images.githubusercontent.com/86683516/178579051-fcb67c51-1150-4421-9670-0a0e4ea6b573.png)
FYI, I'm a light user of ArcPro on desktop.    I use CAD, AGOL and Global Mapper heavily, but very light use of ArcPro (mostly managing online layers and running modelbuilder models).    If there's some kind of best practice recommendations for the install itself, project location, installed tools etc, there's a good chance I'm not following them.

**Comment by giswqs** [comment]
Try out the latest version v2.2.0. Feel free to reopen the issue if the problem persists.
