### ISSUE TITLE
No classification data

### ISSUE THREAD

**Issue by geojmm** [giswqs/WhiteboxTools-ArcGIS#39]
Used machine learning tools to create classification data using the Kmeans cluster. The processing shows to be successful, however, we have no outputs in the specified folder. I am running the toolbox on ArcGIS desktop 10.8.1.
Thank you

**Comment by giswqs** [comment]
What's the message shown in the processing history?

**Comment by geojmm** [comment]
![image](https://user-images.githubusercontent.com/5365067/198275491-54280cd3-4889-4d20-b22e-640be8abe29d.png)

**Comment by jblindsay** [comment]
First, this tool requires a license for the General Toolset Extension and if you do not have a valid license, it will not work. But beyond that, the tool, like the entire Whitebox Platform, does not support the afr file format. The input should be two or more rasters of one of the supported raster file formats (e.g. GeoTIFF).

**Comment by giswqs** [comment]
@geojmm As @jblindsay pointed out, you need to change your input raster format to GeoTIFF or other supported formats, see https://github.com/jblindsay/whitebox-tools#5-supported-data-formats
