### ISSUE TITLE
new wtb release falis when trying to run geomorphons on ArcGIS pro 3.0.0

### ISSUE THREAD

**Issue by rengifoo** [giswqs/WhiteboxTools-ArcGIS#42]
Hi guys !
Congratulations on this great release.
 Below the error, I get when trying to run geomorphons in ArcGIS pro 3.0.0

Traceback (most recent call last):
File "", line 13623, in execute
TypeError: geomorphons() got an unexpected keyword argument 'tdist'

Failed to execute (Geomorphons).

PS: it works perfectly when I run it using wtb runner.

Best
regards
Rengifo Ortega

**Comment by giswqs** [comment]
@rengifoo This bug has been fixed. Please download the update version and try again.

**Comment by rengifoo** [comment]
Thanks a lot  !
I just tried and it worked like a charm
Best regards


Mvh
Rengifo Ortega
GIS-koordinator | Seksjon Miljøledelse anlegg | Avd. Miljø, Oslo

(+47) 45 84 50 58 |  ***@***.******@***.***>
www.multiconsult.no<http://www.multiconsult.no/>
[Multiconsult]
