### ISSUE TITLE
Processes works well for random forest classification but didn't generate a output raster

### ISSUE THREAD

**Issue by Geohangger** [giswqs/WhiteboxTools-ArcGIS#45]
Hello, thanks for the great work.

I used the random forest classifier in WBT. Everything works fine and no error occurred. However, the output raster did not generate. I have tried to change the folder and output names, but nothing helps.  Any ideas of what could cause this problem? My ArcGIS Pro's version is 3.0.

Cheers,
Hang

**Comment by jblindsay** [comment]
This tool requires a license. Please see [here](https://www.whiteboxgeo.com/whitebox-toolset-extension/) for details.

**Comment by Geohangger** [comment]
Thank you for the response, I will purchase a license.
