### ISSUE TITLE
LiDAR Join tool fails when executed from ArcGIS Pro (v2.7.1)

### ISSUE THREAD

**Issue by michelin-pr** [giswqs/WhiteboxTools-ArcGIS#47]
Tried to input two LAS files to join them and assigned the output with the .LAS extension. However, the tool fails immediately after execution with the following error: 

> Traceback (most recent call last):
>   File "<string>", line 20731, in execute
>   File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1255, in Describe
>     return gp.describe(value, data_type)
>   File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 383, in describe
>     self._gp.Describe(*gp_fixargs(args, True)))
> OSError: "'C:MY PATH TO LIDAR FILE\USGS_LPC_PR_PRVI_D_2018_19QGA40004500.las'" does not exist
>  Failed to execute (LidarJoin).

The LiDAR files DO exist on the specified paths.
![image](https://user-images.githubusercontent.com/74156287/228567108-433e809f-fe03-4c47-9feb-20a91bb175a2.png)
 
 
 PS. Thanks to everyone working on this project!

**Comment by giswqs** [comment]
Try a file path without spaces in it.

**Comment by michelin-pr** [comment]
That worked. Thanks!
